#!/bin/bash
echo "CB_SYSTEM_KEY: $CB_SYSTEM_KEY" 
echo "CB_SYSTEM_SECRET: $CB_SYSTEM_SECRET" 
echo "CB_SERVICE_ACCOUNT: $CB_SERVICE_ACCOUNT" 
echo "CB_SERVICE_ACCOUNT_TOKEN: $CB_SERVICE_ACCOUNT_TOKEN"


export CB_SYSTEM_KEY=$CB_SYSTEM_KEY 
export CB_SYSTEM_SECRET=$CB_SYSTEM_SECRET 
export CB_SERVICE_ACCOUNT=$CB_SERVICE_ACCOUNT 
export CB_SERVICE_ACCOUNT_TOKEN=$CB_SERVICE_ACCOUNT_TOKEN